FROM ros:humble

RUN apt update && \
    apt install -y software-properties-common && \
    apt install -y ros-humble-demo-nodes-cpp && \
    apt install -y python3-colcon-common-extensions && \
    apt upgrade -y

RUN apt install -y nano

RUN apt install -y ros-humble-rqt

RUN apt install -y ros-humble-turtlesim

RUN apt install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools && \
    apt install -y dbus-x11 x11-xserver-utils

ENV QT_QPA_PLATFORM=xcb

RUN apt-get install -y python3 python3-pip && \
    pip install pyserial

RUN mkdir -p /wolvi/src

RUN apt install -y python3.10-tk

RUN apt install -y python3-pip

RUN apt install -y python3.10-venv

ENV PYTHONPATH=/wolvi/src:/usr/local/lib/python3.8/site-packages

COPY courier /usr/share/fonts/truetype/courier 

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /root/.bashrc && \
    echo "source /wolvi/install/setup.bash" >> /root/.bashrc

CMD ["bash", "-c", "\
    source /opt/ros/humble/setup.bash && \
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash && \
    source /wolvi/install/setup.bash && \
    exec bash"]

# Afegit per poder engegar el fitxer de Python
RUN apt install -y python3-rpi.gpio

CMD ["python3", "-u", "/wolvi/src/robot/startup_rasp/startup.py"]
