FROM ros:humble

RUN apt update && \
    apt install -y software-properties-common && \
    apt install -y ros-humble-demo-nodes-cpp && \
    apt install -y python3-colcon-common-extensions
    
RUN apt install -y ros-humble-rqt && \
    apt install -y ros-humble-rqt-common-plugins
    
RUN apt install -y ros-humble-turtlesim

RUN apt install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools && \
    apt install -y dbus-x11 x11-xserver-utils
    
ENV QT_QPA_PLATFORM xcb
   
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /root/.bashrc

CMD ["bash", "-c", "\
    source /opt/ros/humble/setup.bash && \
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash && \
    exec bash"]

